version: 2
jobs:
  build:
    docker: 
      - image: circleci/node:8.1.4-browsers
    steps:
      - checkout
      - run: 
          name: Install Dependencies
          command: |
            yarn install
            cd react
            yarn install
            cd ../angular
            yarn install
            cd ..
      - run:
          name: Install Dev Dependencies
          command: |
            yarn install --dev
            cd progress/react
            yarn install --dev
            cd ../angular
            yarn install --dev
            cd ..
            cd ..
      - run:
          name: Build Packages
          command: yarn build
      - run:
          name: Verify SVG Build Artifacts
          command: yarn test:svg
      - run:
          name: Verify Progress Icon Build Artifacts
          command: |
            cd progress/react
            yarn build
            cd ../angular
            yarn build  
            cd ..
            cd ..
            yarn test:progress